### ISSUE TITLE
Error parsing fasta index line

### ISSUE THREAD

**Issue by tantrev** [gpertea/gffread#1]
When trying to run gffread on the latest mouse genome ( ftp://ftp.ensembl.org/pub/release-84/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz ), I receive the following error:

```
Error parsing fasta index line: 
1
```

Any idea what's going on?  Thank you in advance.

**Comment by tantrev** [comment]
Also, I only receive this error with the latest gffread build.  I don't receive it when using the gffread from cufflinks v2.2.1.

**Comment by gpertea** [comment]
Can I get the full command line which triggers this error? I suppose you are trying to pull the sequence of some mouse transcripts, but it's good to know exactly how.

**Comment by gpertea** [comment]
Got it, it was a bug in a base class modified recently - sorry about this, should be corrected in v0.9.6 - thank you for reporting this error.

**Comment by rspreafico** [comment]
Hi, I noticed an issue with FASTA indexing that may be related to this previous bug. 

I run gffread 0.9.6 to extract FASTA sequences using a GTF file using the following command:

`gffread -w transcriptome.fa -g genome.fa genes.gtf`

If the genome.fa is already indexed using samtools faidx, everything goes smoothly. However, if genome.fa is not indexed, then gffread will index it, and then it will extract the sequences of interest using the GTF file. However, I noticed issues in transcriptome.fa generated by gffread after it indexes a genome (inconsistent sequences, line breaks, extra Ns...), but not when the index is already present. Therefore, I compared the FASTA index generated by gffread with the index generated by samtools faidx, and I realized they are different, as follows.

Head of index using samtools:
```
meta1_chr_1_q   7786680 23      60      61
meta1_chr_2_q   5268940 7916504 60      61
meta1_chr_3_q   5034817 13273283        60      61
```

Head of index using gffread:
```
meta1_chr_1_q   7916458 23      61      61
meta1_chr_2_q   5356756 7916504 61      61
meta1_chr_3_q   5118731 13273283        61      61
```

I then tried generating a FASTA index using the gffread utility shipped with Cufflinks 2.2.1, and that generates a FASTA index identical to that generated by samtools.

Thank you.

**Comment by gpertea** [comment]
Thank you so much for reporting this bug, I missed it because I used only pre-existing indexes created by samtools lately.. It looks like some of the later changes to the code (post-cufflinks) have been using some "improvements" which apparently messed up the character counting per line there.. Now I know where to look in the code thanks to your detailed observations. Thanks again!

**Comment by gpertea** [comment]
Fixed in `gclib` repository.
