### ISSUE TITLE
Link to precompiled OSX binary on jhu.edu broken

### ISSUE THREAD

**Issue by cbrueffer** [gpertea/gffread#11]
Hi Geo,

the link to the precompiled OSX package for gffread 0.9.9 on http://ccb.jhu.edu/software/stringtie/gff.shtml under "Obtaining gffread" is broken.

Is there a precompiled package available?

**Comment by gpertea** [comment]
There is now :) -- thank you for pointing out this issue, I must have forgotten to fire up that VM to build & upload this binary..

**Comment by cbrueffer** [comment]
Super, thanks! That means I can update the gffread bioconda recipe :-)
