### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by mick42-star** [gpertea/gffread#124]
Hi, I installed gffread with the command, but there are some error occurred. Could you please give some suggestions?

git clone https://github.com/gpertea/gclib
git clone https://github.com/gpertea/gffread
cd gffread
make release 

/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/GBase.cpp -o ../gclib/GBase.o
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/GArgs.cpp -o ../gclib/GArgs.o
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/GFaSeqGet.cpp -o ../gclib/GFaSeqGet.o
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/gdna.cpp -o ../gclib/gdna.o
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/codons.cpp -o ../gclib/codons.o
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/gff.cpp -o ../gclib/gff.o
../gclib/gff.cpp: In constructor 'BEDLine::BEDLine(GffReader*, const char*)':
../gclib/gff.cpp:263:14: warning: 'bstart' may be used uninitialized in this function [-Wmaybe-uninitialized]
  263 |      bstart[b]=t[11]+i+1;
      |              ^
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/GStr.cpp -o ../gclib/GStr.o
../gclib/GStr.cpp: In static member function 'static GStr::Data* GStr::new_data(const char*, uint)':
../gclib/GStr.cpp:42:18: warning: 'data' may be used uninitialized in this function [-Wmaybe-uninitialized]
   42 |         data->cap=len+addcap;
      |         ~~~~~~~~~^~~~~~~~~~~
../gclib/GStr.cpp: In constructor 'GStr::GStr(const char*, uint)':
../gclib/GStr.cpp:42:18: warning: 'data' may be used uninitialized in this function [-Wmaybe-uninitialized]
   42 |         data->cap=len+addcap;
      |         ~~~~~~~~~^~~~~~~~~~~
../gclib/GStr.cpp:38:15: note: 'data' was declared here
   38 |         Data* data;
      |               ^~~~
../gclib/GStr.cpp: In member function 'GStr& GStr::replace(const char*, const char*)':
../gclib/GStr.cpp:85:24: warning: 'data' may be used uninitialized in this function [-Wmaybe-uninitialized]
   85 |         data->ref_count++;
      |         ~~~~~~~~~~~~~~~^~
../gclib/GStr.cpp:38:15: note: 'data' was declared here
   38 |         Data* data;
      |               ^~~~
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c ../gclib/GFastaIndex.cpp -o ../gclib/GFastaIndex.o
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c gff_utils.cpp -o gff_utils.o
gff_utils.cpp: In function 'void printTableData(FILE*, GffObj&, bool)':
gff_utils.cpp:299:9: warning: enumeration value 'ctfGFF_all_attrs' not handled in switch [-Wswitch]
  299 |   switch(tableCols[i].type) {
      |         ^
/data/apps/linux-centos8-cascadelake/gcc-9.2.0/gcc-9.3.0-bnvby67rgbqevwsd264rgz44xucnkhpm/bin/g++ -O3 -DNDEBUG -Wall -Wextra -std=c++11 -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -fno-exceptions -fno-rtti -Wno-class-memaccess -c gffread.cpp -o gffread.o
g++ -g -o gffread ../gclib/GBase.o ../gclib/GArgs.o ../gclib/GFaSeqGet.o ../gclib/gdna.o ../gclib/codons.o ../gclib/gff.o ../gclib/GStr.o ../gclib/GFastaIndex.o gff_utils.o gffread.o 

gffread -h
gffread: command not found

**Comment by NayeliGutierrez** [comment]
I am having the same error. Did you manage to fix it?

**Comment by gpertea** [comment]
The `make release`  command only creates the `gffread` executable  in the current directory. If you want to use it just by invoking `gffread`, that executable should be copied somewhere in your shell's PATH (depending on your shell configuration). 

Running `./gffread -h` should work if the program exists in the current directory, but that's not a convenient way of using a Linux program.. Instead, the program should be in one of the directories specified in your executable search list of directories (which is what the `$PATH` environment variable is for), so you can conveniently invoke it from anywhere.

**Comment by NayeliGutierrez** [comment]
It worked, thank you so much!
