### ISSUE TITLE
GTF error for GFF3 file

### ISSUE THREAD

**Issue by sejmodha** [gpertea/gffread#20]
Hi There,

I am using gffread to extract CDS sequences using GFF and fasta files and I get the following error which seems to assume that I have provided a GTF file instead of GFF3.

`gffread -y prots_file.fasta -g file.fasta file.gff3`

`Warning: invalid GTF record, transcript_id not found:`

**Comment by gpertea** [comment]
Showing an example of your input (and perhaps the complete error message) would've been very helpful.
gffread doesn't assume anything about the input (unless you "misled" it with some incorrectly formatted lines), it first looks for an "ID=" (or "Parent=") in your lines (for seemingly "transcript" or "exon" features) and only if those are not found if looks for "transcript_id" and if that is not found either it will complain  about it (so indeed it would've been better to have said "neither ID nor Parent nor transcript_id were found:" ).
So can I see a few lines around&including the line that triggered that error message? I hope your CDS lines have the "Parent=" attribute in there, if that were indeed a GFF3 file. Admittedly gffread can sometimes get confused by extraneous features that can be found in some needlessly detailed GFF3 files..

**Comment by sejmodha** [comment]
Hi, 

I am using a gff3 file downloaded from: http://pathogenseq.lshtm.ac.uk/knowlesi_1/strain_A1_H.1.Icor.gff3.gz. There were few malformatted lines e.g. beginning with ### (not the comments lines!) that had to be removed but the gffread was unable to accept this file as valid gff3 file.

**Comment by gpertea** [comment]
The updated version of gclib (the master branch) includes a fix for this, so if you build gffread from github with the updated gclib, this should work now. So the fix will be in the next official release of gffread.
Alternatively you can filter out the contig features before feeding the file into gffread, something like this:
```
zcat strain_A1_H.1.Icor.gff3.gz | grep -v -P '\tcontig\t' | gffread - -g /path/to/genome.fa -x out_CDS.fa 
```
(assuming you wanted to get the CDS sequences for all those transcripts there).
