### ISSUE TITLE
Documentation for "linpack" references?

### ISSUE THREAD

**Issue by tseemann** [gpertea/gffread#24]
Trying to package this, and seeing `linpack` references here:

https://github.com/gpertea/gffread/blob/master/prep_linux.sh

Do you depend on `linpack` ?

**Comment by gpertea** [comment]
no idea what that is, for me it was just a var name in that bash script.. Thank you for looking into packaging this, indeed I should do a better job with the gclib dependency. Apologies, I am away for the weekend and not having a proper working space right now, I'll get back to you on the other issues as soon as possible.

**Comment by TMiguelT** [comment]
Yes that looks like a misunderstanding. The author just wanted a variable to represent the linux archive, and it happened to have the same name as LINPACK. I would close this issue.
