### ISSUE TITLE
merging overlapping/adjacent feature

### ISSUE THREAD

**Issue by StoltzfusJ** [gpertea/gffread#30]
I'm having trouble with gffread merging exons together, and I'm uncertain as to the reason.
If I run the following through gffread (version that comes with cufflinks v2.2.1):

`Twitchin_Composite_20181005	.	mRNA	1	12829	.	+	.	ID=mrna0001;Name=twitchin
Twitchin_Composite_20181005	.	exon	1	1606	.	+	.	ID=exon00001;Parent=mrna0001
Twitchin_Composite_20181005	.	exon	1607	12829	.	+	.	ID=exon00002;Parent=mrna0001`

I get the following error:
`GFF Warning: merging overlapping/adjacent feature segment exon (1607-12829) with exon (1-1606) for GFF ID mrna0001 on Twitchin_Composite_20181005`

I'm not sure what to change in the annotation file to avoid this error.  Any help would be appreciated.

**Comment by gpertea** [comment]
[side note: that's not really an "error", it's just a warning there informing you that gffread tried to correct something that it perceived as possibly wrong in the user input..]

gffread was written mostly for eukaryotic annotation and it always had this builtin assumption that introns should be at least 4-5 nucleotides long (many other programs assume at least 10 and I don't think there is biological evidence of introns shorter than that in eukaryotes). 
In your example the intron seems to have a length of.. 0, right? That would mean that in fact there isn't any intron there, so gffread decided to "fix that for you" by joining the two exons into one (1-12829), and warned you about having to do that in the process. 
But please let me know if there is just cause why those two exons may not be lawfully joined together ("..or forever hold your peace" - joking of course :) ).

**Comment by StoltzfusJ** [comment]
Ah!  I think that may be it.  I'm using a Trinity output contig as my reference, and thus there are no introns between the exons.  I'm looking to do differential expression of the exons along this reference.  Is there a way to suppress this other than going into the *.fasta file and adding a string of Ns between the exons?
Thanks for the fast reply.

**Comment by StoltzfusJ** [comment]
Right.  I too was afraid that would be the answer, but thanks for the information and reply.  It's far better to know than banging my head against the wall.  Making whole "fake" scaffolds is a bit cumbersome, so I'll see if I can dream up another way; if not, at least I know the minimum length for my fake introns :-)
