### ISSUE TITLE
Error in gffread to extract transcript seqs

### ISSUE THREAD

**Issue by sarahharvey88** [gpertea/gffread#31]
It keeps returning the error that it can't find the fasta records for these files. I am using the command:

gffread -w Lactuca_sativa_lettuce_transcriptome.fa -g Lactuca_sativa_lettuce.fa Lactuca_sativa_lettuce_annos.gff

As part of the script it produced an index which looks correct as it matches the chronosomes in the gff file:
lcl|Lsat_1_v8_lg_4      377529803       20      80      81
lcl|Lsat_1_v8_lg_5      339640866       382248966       80      81
lcl|Lsat_1_v8_lg_8      309698552       726135363       80      81
lcl|Lsat_1_v8_lg_3      257910700       1039705167      80      81
lcl|Lsat_1_v8_lg_2      217164977       1300839771      80      81
lcl|Lsat_1_v8_lg_1      214790941       1520719331      80      81
lcl|Lsat_1_v8_lg_9      204289203       1738195179      80      81
lcl|Lsat_1_v8_lg_7      195685357       1945038018      80      81
lcl|Lsat_1_v8_lg_6      193110136       2143169462      80      81
lcl|Lsat_1_v8_lg_0      89688949        2338693495      80      81

Warning: couldn't find fasta record for 'Lsat_1_v8_lg_0'!
Warning: getSpliced(NULL,.. ) called!
Warning: couldn't find fasta record for 'Lsat_1_v8_lg_0'!
Warning: getSpliced(NULL,.. ) called!
Warning: couldn't find fasta record for 'Lsat_1_v8_lg_0'!
Warning: getSpliced(NULL,.. ) called!
Warning: couldn't find fasta record for 'Lsat_1_v8_lg_0'!

Any ideas? The Fasta and GFF file were downloaded from here https://genomevolution.org/coge/GenomeInfo.pl?gid=28333

Thanks
Sarah

**Comment by gpertea** [comment]
The error messages seem to suggest that the `lcl|` prefix is missing for the chromosome/contig identifiers in the 1st column of the GFF. Is that the case? That `lcl|` prefix is there for entries in the FASTA file though (as your sample of the index file shows). Hence the name mismatch..

**Comment by sarahharvey88** [comment]
Oh thank you, fixing the genome file fixed it. Apologies I thought lcl was a normal part of the index file!
