### ISSUE TITLE
release for 0.10.6 on gff utilities website

### ISSUE THREAD

**Issue by arielzn** [gpertea/gffread#32]
Hi,

For packaging purposes with [easybuild](https://easybuild.readthedocs.io), it's more useful to have the tarball for the complete compatible source (i.e. gffread+gclib) on the GFF utils website
http://ccb.jhu.edu/software/stringtie/gff.shtml

I can see that for gffcompare you are providing there this kind of tarball for 0.10.6.

Is there a reason for which you didn't follow for gffread ?

thanks.

**Comment by gpertea** [comment]
Apologies for this -- there is no reason, I should've updated those tarballs on the website when I tagged the release. You are very correct that the complete source for this program is best retrieved that way.
I just pushed those tarballs a few minutes ago -- thank you for reminding me!
