### ISSUE TITLE
BUG? single exon transcripts on - strand incorrectly discarded

### ISSUE THREAD

**Issue by dstern** [gpertea/gffread#35]
I am using gffread to convert to combine exon and three_prime_utr features into a single transcript. This works well, except for one specific case. Single exon records with a three_prime_utr are not included when they fall on the - strand. + strand records work fine.

Here is the warning (one of multiple)
Warning: unrecognized component record with ID g3829_2.t1 discarded.
When I look at this in the original file

ScPoQx8_9972;HRSCAF=12060	UTRme	three_prime_UTR	21573459	21573464	77.0	-	.	Parent=g3829_2.t1
ScPoQx8_9972;HRSCAF=12060	AUGUSTUS	exon	21573465	21573588	.	-	.	Parent=g3829_2.t1

All the records that fail are - strand single exon.

**Comment by gpertea** [comment]
Is this happening with the current version of gffread? I copied those two lines in a file test.gff (replacing spaces with tabs of course) and gffread v0.11.4 (current version) shows this output for `gffread -v test.gff`:
```
Warning: exon feature found before transcript ID g3829_2.t1
   .. loaded 1 genomic features from test.gff
# ./gffread -v test.gff
# gffread v0.11.4
##gff-version 3
ScPoQx8_9972;HRSCAF=12060	UTRme	transcript	21573459	21573588	.	-	.ID=g3829_2.t1
ScPoQx8_9972;HRSCAF=12060	UTRme	exon	21573459	21573588	77.0	-	.	Parent=g3829_2.t1
```
The warning there makes sense for GFF3 input but I can see the UTR being merged into the exon as expected. 
Perhaps this was indeed a bug in an older version of gffread, but I can't seem to be able to reproduce it with the current version.

**Comment by dstern** [comment]
Appears to have been a version issue.
Works with current version.
Sorry to bother you with this and thanks for your help.
D

On May 7, 2019, at 7:54 AM, Geo Pertea <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this happening with the current version of gffread? I copied those two lines in a file test.gff (replacing spaces with tabs of course) and gffread v0.11.4 (current version) shows this output for gffread -v test.gff:

Warning: exon feature found before transcript ID g3829_2.t1
   .. loaded 1 genomic features from test.gff
# ./gffread -v test.gff
# gffread v0.11.4
##gff-version 3
ScPoQx8_9972;HRSCAF=12060       UTRme   transcript      21573459        21573588        .       -       .ID=g3829_2.t1
ScPoQx8_9972;HRSCAF=12060       UTRme   exon    21573459        21573588        77.0    -       .       Parent=g3829_2.t1


The warning there makes sense for GFF3 input but I can see the UTR being merged into the exon as expected.
Perhaps this was indeed a bug in an older version of gffread, but I can't seem to be able to reproduce it with the current version.
