### ISSUE TITLE
missing gene_id

### ISSUE THREAD

**Issue by olechnwin** [gpertea/gffread#37]
Hi,

I am trying to convert my gff file which was a liftover from gencode hg19 to gtf file for use with cell ranger. This is the command I ran:
The resulting gtf file has some lines that do not have gene_id.

Example of those lines:

in gtf:

`10201   HAVANA  exon    627357  627553  .       -       .       transcript_id "ENST00000304883.2";`
`10201   HAVANA  CDS     627357  627553  .       -       0       transcript_id "ENST00000304883.2";`

in gff:

`10201   HAVANA  exon    627357  627553  .       -       .       ID=exon:ENST00000304883.2:4;Parent=ENST00000304883.2;gene_id=ENSG00000169836.4;transcript_id=ENST00000304883.2;gene_type=protein_coding;gene_status=KNOWN;gene_name=TACR3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=TACR3-001;exon_number=4;exon_id=ENSE00001134536.1;level=2;protein_id=ENSP00000303325.2;ccdsid=CCDS3664.1;havana_gene=OTTHUMG00000131124.1;havana_transcript=OTTHUMT00000253804.1;tag=basic,appris_principal,CCDS`

`10201   HAVANA  CDS     627357  627553  .       -       0       ID=CDS:ENST00000304883.2:4;Parent=ENST00000304883.2;gene_id=ENSG00000169836.4;transcript_id=ENST00000304883.2;gene_type=protein_coding;gene_status=KNOWN;gene_name=TACR3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=TACR3-001;exon_number=4;exon_id=ENSE00001134536.1;level=2;protein_id=ENSP00000303325.2;ccdsid=CCDS3664.1;havana_gene=OTTHUMG00000131124.1;havana_transcript=OTTHUMT00000253804.1;tag=basic,appris_principal,CCDS`

I read some of the similar issues posted but I still cannot tell whether this is the intended behavior. I'm wondering whether I just remove the lines without gene_id in the gtf file without any adverse effect.

Thank you in advance for your help.

**Comment by gpertea** [comment]
In your gff file, is there a _transcript_ or _mRNA_ feature line (besides the _exon_ and _CDS_ feature lines you showed there)? 
 The complete GFF format for a transcript record should include a line for the transcript feature itself (in this example the line should have `ID=ENST00000304883.2;`), not just the child _exon_ and _CDS_ features. Do you have such line in that gff? gffread expects that transcript line in the gff and takes the gene ID from there, not from the lower-level exon features as you seem to expect.

But by default gffread discards any non-essential attributes from the low-level exon/CDS features -- and it certainly does not even attempt to recover gene ID and other _higher_ level attributes from exon-level attributes. It is also extremely redundant to have all those gene and transcript attributes duplicated for every exon and CDS, as you are showing in this example..

**Comment by olechnwin** [comment]
You are right. There is a line for the transcript feature in gff. Although, that line doesn't have gene ID. it looks like it takes the gene ID from the lower-level exon features?

in gff:

`10201   HAVANA  transcript      621900  753784  .       -       .       ID=ENST00000304883.2`
`10201   HAVANA  exon    621900  625863  .       -       .       ID=exon:ENST00000304883.2:5;Parent=ENST00000304883.2;gene_id=ENSG00000169836.4;transcript_id=ENST00000304883.2;gene_type=protein_coding;gene_status=KNOWN;gene_name=TACR3;transcript_type=protein_coding;transcript_status=KNOWN;transcript_name=TACR3-001;exon_number=5;exon_id=ENSE00001131476.2;level=2;protein_id=ENSP00000303325.2;ccdsid=CCDS3664.1;havana_gene=OTTHUMG00000131124.1;havana_transcript=OTTHUMT00000253804.1;tag=basic,appris_principal,CCDS`


in gtf:

`10201   HAVANA  transcript      621900  753784  .       -       .       transcri                                                           pt_id "ENST00000304883.2"; gene_id "ENSG00000169836.4"; transcriptID "ENST000003                                                           04883.2"; gene_type "protein_coding"; gene_status "KNOWN"; gene_name "TACR3"; tr                                                           anscript_type "protein_coding"; transcript_status "KNOWN"; transcript_name "TACR                                                           3-001"; level "2"; protein_id "ENSP00000303325.2"; ccdsid "CCDS3664.1"; havana_g                                                           ene "OTTHUMG00000131124.1"; havana_transcript "OTTHUMT00000253804.1"; tag "basic                                                           ,appris_principal,CCDS";`

I actually didn't know what to expect. Thank you so much for taking the time to explain.

**Comment by gpertea** [comment]
> it looks like it takes the gene ID from the lower-level exon features?

Who/what does that (and why) ? :)
It looks like the GFF file was rather clumsily generated from a GTF by somehow ignoring the "transcript" feature lines in the GTF and just converting the exon and CDS features and adding a basic parent transcript line which lacks any other attributes.. I hope that conversion wasn't performed by an older version of gffread.. :)
Since you already have a GTF there, with 'transcript' features and all -- why can't you directly use that one with cell ranger? Never used cell ranger, but if the problem is that it doesn't like the _transcript_ feature lines in GTF you could perhaps use something like grep to just filter out those lines..

**Comment by olechnwin** [comment]
Thank you so much for your help and yes I am going to use the GTF I have with the lines without gene_id deleted.

The GFF was an output from flo annotation pipeline that lift gencode gff annotation to our denovo assembled genome. I don't think it was using old version of gffread. Hopefully? :)
