### ISSUE TITLE
gffread vs cufflinks

### ISSUE THREAD

**Issue by mestia** [gpertea/gffread#40]
Could you please clarify what is the relation of `gffread` to `gffread` in `cufflinks` suite?
As far as I see they share the same codebase. Is there any reason to use `gffread` from `cufflinks` instead of this project?
Thank you.

**Comment by gpertea** [comment]
The programs do indeed have a common code base, but this here is the _main_, actively maintained code base of gffread, while the cufflinks version of gffread is more of a "back-ported" version of the code, as it has a much slower update/release cycle (being tied into the cufflinks release cycle). The cufflinks version only gets sporadic updates of the gffread code coming from _this repository_. At the moment this version here has quite a few new features, improvements and fixes as I haven't ported the recent changes into the cufflinks source tree for a long time (though I do plan to keep them in sync as much as possible - which is quite difficult given the huge difference in the release pace).  
One possible reason to use the cufflinks version (which is considerably older, generally) is that was a somewhat stable version, so when I screw up a release/update of gffread in this "bleeding edge" repository, so falling back to that older cufflinks version may provide a workaround in that situation..

**Comment by mestia** [comment]
Thank you, but why shipping cufflinks with duplicated code at all? I think it will be easier to remove gffread from cufflinks and have only one up-to-date gffread.

**Comment by gpertea** [comment]
It makes sense, I agree and this might become the case for the next release of Cufflinks -- it's up to cufflinks project owner(s) - I guess I could discuss this with them. gffread was historically packaged with Cufflinks and only after the last release, as the Cufflinks release schedule slowed down significantly, I then wanted to add new features to gffread so I started to maintain/release it separately, that's all.
