### ISSUE TITLE
Cannot extract attributes when specifying the --table parameter

### ISSUE THREAD

**Issue by jma1991** [gpertea/gffread#46]
I am trying to get a table containing just the transcript_id and gene_id attributes from the following GTF file hosted by Ensembl:

`https://ftp.ensembl.org/pub/release-99/gtf/mus_musculus/Mus_musculus.GRCm38.99.gtf.gz`

The command I am using is pasted below:

`gffread GRCm38.p6.annotation.gtf --table gene_id,transcript_id > output.txt`

The output from this command is just a text file containing a dot for each attribute:

```
head output.txt
.	.
.	.
.	.
.	.
.	.
.	.
.	.
.	.
.	.
.	.
```

I am not sure if I'm specifying the attributes incorrectly of if there is something else wrong? I am using version 0.11.6

Thank you,
James

**Comment by gpertea** [comment]
No, you were correct, I just haven't properly tested that `--table' option for GTF input, and "core" attributes like ID and geneID have a special treatment internally. 

I fixed this into the 199fdea commit, should be in the v0.11.7 release (or you can grab/compile from the master branch right now).

**Comment by jma1991** [comment]
Just compiled from master branch, works as expected. Thank you for the quick fix.
