### ISSUE TITLE
Release v0.11.7 to CCB software download page

### ISSUE THREAD

**Issue by jma1991** [gpertea/gffread#49]
I would like to update the bioconda recipe for gffread to the latest release (v0.11.7) but it requires the compiled software to be available on the CCB software download page (http://ccb.jhu.edu/software/stringtie/dl).

The current recipe for v0.11.6 is available here: 

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gffread/meta.yaml

Please could you host the latest release on the CCB page so I can update the version number on the current recipe?

**Comment by gpertea** [comment]
Done - thank you for the reminder!

**Comment by jma1991** [comment]
Excellent, thank you very much
