### ISSUE TITLE
Line-endings from genomic fasta input are doubled or misplaced in cds fasta output

### ISSUE THREAD

**Issue by culpinnis** [gpertea/gffread#5]
Hi,

If I work with fasta input files (parameter -g ) which are split after 80 characters, the newlines are also present (e.g. doubled or misplaced) in the output fasta files (using parameter -x or -y). 
Most of the gff entries are not starting at the beginning of an fasta line, so the newlines are shifted in the resulting (translated) cds fasta.
For cds sequences this is not critical, because the newlines can be easily removed. But the reading frame of the translated protein sequences get shifted by the newlines, which results in wrong amino acids.

I am using gffread v0.9.6. I hope my description is meaning- and helpful. 

Kind regards
Chris

**Comment by gpertea** [comment]
Indeed there was a bug related to indexing the genome FASTA file -- I think this is what your bug report is also about (hope so). This was fixed recently and the new version (0.9.8) should work correctly now. If you rebuild from github remember to pull the latest version of `gclib` as well, the fixes are actually in there, not in the main gffread source.
