### ISSUE TITLE
citation for gffread

### ISSUE THREAD

**Issue by fgypas** [gpertea/gffread#53]
Hi
How can I cite gffread? I can't find a doi.
Thank you in advance
Foivos

**Comment by gpertea** [comment]
Sorry for the delay. 
We've recently submitted an application note (for gffread and gffrcompare) but not sure when/if it's gonna be published. I could probably generate a doi for this github repository with Zenodo but I don't really like that option and it doesn't seem to make much sense. So for now, sorry, no doi -- perhaps you can use a simple url citation for its official home page here: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread

**Comment by fgypas** [comment]
Thanks a lot. It's not very urgent at the moment, so maybe you will have a doi once we submit. I will ping again in the future.

**Comment by gpertea** [comment]
Just generated one with Zenodo, it turns out it is required for submitting in some cases.
[DOI: 10.5281/zenodo.3739573](https://doi.org/10.5281/zenodo.3739573)

**Comment by gpertea** [comment]
Sorry, that's just a DOI, but no official publication yet.

**Comment by gpertea** [comment]
The actual paper "GFF Utilities: GffRead and GffCompare" has just been published (awaiting reviews) by F1000Research
[DOI: 10.12688/f1000research.23297.1](http://dx.doi.org/10.12688/f1000research.23297.1)
This is the DOI that should be used for citations for GffRead and GffCompare.

**Comment by fgypas** [comment]
Congratulations and thanks a lot for the doi.
