### ISSUE TITLE
 GTF to GFF3: recover (or infer) gene feature

### ISSUE THREAD

**Issue by LehmannN** [gpertea/gffread#54]
I am converting GTF (from UCSC) to GFF3 and I thought I could recover the "gene" feature with the command: `gffread -E input.gtf -o- > output.gff` as specified here: https://www.biostars.org/p/224372/.
The input GTF has these features (no gene feature):
3UTR
5UTR
CDS
exon
start_codon
stop_codon
transcript.

However, after running gffread, the output does not include any 'gene' feature. I tried with the parameter '--keep-genes' but it does not change anything. Some tools really do need a 'gene' feature so I wondered if I can obtain this with gffread or should I look for some other ways. 

Thanks for the help

Input GTF: https://hgdownload.soe.ucsc.edu/goldenPath/galGal6/bigZips/genes/galGal6.ncbiRefSeq.gtf.gz

**Comment by gpertea** [comment]
The `--keep-genes` option was very basic, it was only intended for GFF3 files and it simply lets through the existing _gene_ features from the input file.
But it should be easy to make it useful for GTF input as well, just to emit a gene feature for the gene_id there (the first time it's seen). I'll take a look and hopefully add this later today.

**Comment by LehmannN** [comment]
Thanks, that would be awesome !

**Comment by gpertea** [comment]
This functionality was just added in the latest commit to master branch (please let me know if it does not behave as expected). Can you build it from here or you'd rather use release packages ?

**Comment by LehmannN** [comment]
The functionality is working in some cases, but some others lead to seg fault. I am still trying to figure it out. If you want to have a look at the data that I used, here is the top 121 lines of the UCSC data (link above): https://gofile.io/d/IvK5Ug . In this case, seg fault occurs at line 111.

**Comment by gpertea** [comment]
Sorry it's my fault,  I rushed that patch and introduced a bug there. Thank you for that head.gtf file, I can see how it crashes and I'll fix it.

**Comment by gpertea** [comment]
Should be fixed now, please let me know if you encounter any more problems with this option.

**Comment by LehmannN** [comment]
Working perfectly ! Thanks again :)
