### ISSUE TITLE
Segfault when --keep-genes is combined with -C

### ISSUE THREAD

**Issue by mrvollger** [gpertea/gffread#56]
Hi, 

When using gffreads with --keep-genes and -C I always get a segfault.

For example:
```
gffread --keep-genes -C ref/gencode.v34.primary_assembly.annotation.gff3 > /dev/null
```
Where the input gff is from: ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.annotation.gff3.gz

Any suggestions?

Thanks in advance!

Best,
Mitchell

**Comment by gpertea** [comment]
This issue was fixed in the latest release.
