### ISSUE TITLE
build failure: GStrSet is not a template

### ISSUE THREAD

**Issue by joelb123** [gpertea/gffread#60]
v0.12.2 and 0.12.3 fail to build under gcc 9 and gcc 10 with the following:

c++ -O2 -pipe -march=native -fpermissive -DNDEBUG -Wall -Wextra -I. -I../gclib -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_REENTRANT -fno-strict-aliasing -std=c++11 -fno-exceptions -fno-rtti -Wno-class-memaccess -O2 -pipe -march=native -fpermissive -c gffread.cpp -o gffread.o
In file included from gffread.cpp:2:
gff_utils.h:123:8: error: ‘GStrSet’ is not a template
  123 | extern GStrSet<> fltIDs;
      |        ^~~~~~~
(many subsequent errors clipped)

v0.12.1 builds and runs for me, provided I use the "-fpermissive" switch on gcc.

clang 10 produces a boatload of error messages.

**Comment by gpertea** [comment]
Strange, I just tried that c++ command on a Linux distro with gcc 10.1.0 and it didn't complain at all. 
Is it possible that the `../gclib` source directory you point at there is not up to date?  
Also, the .tar.gz source package I include with every release should be having the "matching" gclib files packaged in a complete, independent source archive that would be better to use for checking such build issues (to avoid the confusion generated by the fact that gclib is a separate git repo, sorry about that). 

If you want to try that, please get the latest standalone source package (https://github.com/gpertea/gffread/releases/download/v0.12.3/gffread-0.12.3.tar.gz) and see if that has the same build error.. If that happens, could you please send me the output of `c++ -v`  (and perhaps more details about the Linux distro/environment where you are trying these builds) ?

**Comment by joelb123** [comment]
Sorry, it was my mistake arising from version skew between gffread and gclib.  Now that I'm using gclib 0.12.2 the problem disappeared.  I would note that version numbers between gffread and gclib don't always match (like right now), so it's one thing that us build script maintainers have to check for. But thanks for your prompt response.
