### ISSUE TITLE
gffread installation

### ISSUE THREAD

**Issue by xiaolinchu92** [gpertea/gffread#63]
Hi, 
Thanks for the packages.  I would like to convert my gff3 file to gtf file with gffread but got the error "bash: gffread: command not found" in the beginning.  

There is the code to install gclib and gffread:
```
cd software/
git clone https://github.com/gpertea/gclib
git clone https://github.com/gpertea/gffread
cd gffread
make release 
```
Then I tried to use the ggfread with the following code: 

`gffread Analyze/Seq/ref.gff3 -T -o Analyze/Seq/ref.gtf`

The gffread file exists in the folder and are excutable, but it failed with the following error

![image](https://user-images.githubusercontent.com/73734129/97773180-a3a60200-1b88-11eb-849a-6143899cbb33.png)

 
![image](https://user-images.githubusercontent.com/73734129/97773194-be787680-1b88-11eb-88ce-dd7528e7b11f.png)

I am a newbie at analyzing sequencing data.  Could anyone help me to figure out? Thanks in advance.

Xiaolin

**Comment by gpertea** [comment]
_(Linux/Unix shell basics)_ ./gffread should work
