### ISSUE TITLE
Include GTF "transcript_version" attribute in .fa transcript name

### ISSUE THREAD

**Issue by ACastanza** [gpertea/gffread#68]
Hello,

Firstly, thank you for providing this tool, it is by far the most straightforward way to extract sequences from the GTF/gffs+genome.

Before I get into the issue, I'm sorry, I know Ensembl's GTFs are an abomination, but some of us unfortunately need to support them.
The issue I'm having is that Ensembl, but not Gencode GTFs split their transcript ids into two separate fields a "transcript_id" field containing the core transcript identifier, but a separate "transcript_version" attribute.
In the gencode GTFs, as well as both Gencode and Ensembl transcript.fa files, this is is a single identifier where the Transcript id is joined by a "." to the version.

My request is that, gffread would have an optional flag such that when the flag is passed, if the "transcript_version" attribute is detected, it would connect this to the transcript_id attribute (with a .), creating a name for the output .fa that more closely replicates the name that would be expected had Ensembl/Gencode produced the .fa file. 
Ideally, if this flag were passed but the "transcript_version" attribute wasn't present, it would have no effect.

Additionally, it appears that many transcript names in my output .fa file are getting a "CDS=N-M" attribute appended do them, is there a flag to disable this? (I am using -w and want the full sequence, but just need the name not the location of the CDS.)

Thank you!
-Anthony

**Comment by gpertea** [comment]
I recall adding the -L flag to take care of _some other_ Ensembl GTF quirks, but I am pretty sure that it was such a long time ago that this transcript versioning issue wasn't even there at the time (?) , and likely `-L` is now not doing much (or even fails) with the current format -- haven't tested this option in a long time. I guess I could simply reuse that, or add a new `--tver` option.

Agreed also that the CDS info in the FASTA defline shouldn't be enforced as it is now.  I remember I did use that info in some old pipeline so I'll simply add an option to disable it for `-w` output, but I'll leave the default as is to not break some legacy pipeline that might rely on that..

I hope to address these issues tomorrow

**Comment by gpertea** [comment]
The latest tentative release[ v0.12.4](https://github.com/gpertea/gffread/releases/tag/v0.12.4) should have the version-as-a-suffix feature for the `-L` option. 

To disable the CDS info in the FASTA output for -w I added the option `--w-nocds` which should be given to get the "clean" deflines in the `-w` FASTA file.

Can you give these a try, please ? I haven't tested these new changes extensively, let me know if they don't perform as expected.

The version number can be easily merged into IDs for the _GTF_ files provided by Ensembl, but for GFF3 they have a single `version` attribute which applies to the current feature only, so it wasn't that convenient to change all IDs on the fly as I parse each line separately.. Keeping track of partial IDs then merging the version in later is a bit more complex than what I am quickly doing now for their GTF, where I can simply use `gene_version` and `transcript_version` that are available at every level. 
 
For Ensembl GFF3 the `-L` option currently just removes the `gene:` and `transcript:` prefixes currently.. (who thought that adding those incredibly redundant prefixes into the GFF file was a good idea?!?)

**Comment by ACastanza** [comment]
Thanks for the quick work on this! The --w-nocds option appears to be working perfectly, but I can't seem to get the -L option to take. I confirmed that my GTF (I'm testing this with Rattus_norvegicus.Rnor_6.0.101.gtf)  has gene_version and transcript_version fields. I'm using the command:

gffread /ensmbl/rat_ensembl/Rattus_norvegicus.Rnor_6.0.101.gtf -w Rat_Ensembl.fa -g /ensmbl/rat_ensembl/Rattus_norvegicus.Rnor_6.0.dna.toplevel.fa -L -G --w-nocds

But the resulting fasta displays universioned transcript IDs still (albeit ones without the CDS info, which is progress!) (I've also tried it without the -G, I'm not actually sure if that flag does anything or not in this particular mode)

**Comment by ACastanza** [comment]
Follow-up, I just tried it with the human Homo_sapiens.GRCh38.101.gtf and it worked just fine giving a fasta output with transcript versions attached, I'll look into this some more

**Comment by ACastanza** [comment]
Yep, this is super odd, the Human gtf works perfectly:

#!genome-build GRCh38.p13
#!genome-version GRCh38
#!genome-date 2013-12
#!genome-build-accession NCBI:GCA_000001405.28
#!genebuild-last-updated 2020-03
1	havana	gene	11869	14409	.	+	.	gene_id "ENSG00000223972"; gene_version "5"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene";
1	havana	transcript	11869	14409	.	+	.	gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; tag "basic"; transcript_support_level "1";
1	havana	exon	11869	12227	.	+	.	gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; exon_number "1"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; exon_id "ENSE00002234944"; exon_version "1"; tag "basic"; transcript_support_level "1";
1	havana	exon	12613	12721	.	+	.	gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; exon_number "2"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; exon_id "ENSE00003582793"; exon_version "1"; tag "basic"; transcript_support_level "1";
1	havana	exon	13221	14409	.	+	.	gene_id "ENSG00000223972"; gene_version "5"; transcript_id "ENST00000456328"; transcript_version "2"; exon_number "3"; gene_name "DDX11L1"; gene_source "havana"; gene_biotype "transcribed_unprocessed_pseudogene"; transcript_name "DDX11L1-202"; transcript_source "havana"; transcript_biotype "processed_transcript"; exon_id "ENSE00002312635"; exon_version "1"; tag "basic"; transcript_support_level "1";

The rat one does not:

#!genome-build Rnor_6.0
#!genome-version Rnor_6.0
#!genome-date 2014-07
#!genome-build-accession NCBI:GCA_000001895.4
#!genebuild-last-updated 2017-01
1	ensembl_havana	gene	396700	409750	.	+	.	gene_id "ENSRNOG00000046319"; gene_version "4"; gene_name "AABR07000046.1"; gene_source "ensembl_havana"; gene_biotype "processed_transcript";
1	ensembl	transcript	396700	409676	.	+	.	gene_id "ENSRNOG00000046319"; gene_version "4"; transcript_id "ENSRNOT00000044187"; transcript_version "4"; gene_name "AABR07000046.1"; gene_source "ensembl_havana"; gene_biotype "processed_transcript"; transcript_name "AABR07000046.1-202"; transcript_source "ensembl"; transcript_biotype "processed_transcript";
1	ensembl	exon	396700	396905	.	+	.	gene_id "ENSRNOG00000046319"; gene_version "4"; transcript_id "ENSRNOT00000044187"; transcript_version "4"; exon_number "1"; gene_name "AABR07000046.1"; gene_source "ensembl_havana"; gene_biotype "processed_transcript"; transcript_name "AABR07000046.1-202"; transcript_source "ensembl"; transcript_biotype "processed_transcript"; exon_id "ENSRNOE00000493937"; exon_version "1";
1	ensembl	exon	397780	397788	.	+	.	gene_id "ENSRNOG00000046319"; gene_version "4"; transcript_id "ENSRNOT00000044187"; transcript_version "4"; exon_number "2"; gene_name "AABR07000046.1"; gene_source "ensembl_havana"; gene_biotype "processed_transcript"; transcript_name "AABR07000046.1-202"; transcript_source "ensembl"; transcript_biotype "processed_transcript"; exon_id "ENSRNOE00000544646"; exon_version "1";
1	ensembl	exon	399062	399070	.	+	.	gene_id "ENSRNOG00000046319"; gene_version "4"; transcript_id "ENSRNOT00000044187"; transcript_version "4"; exon_number "3"; gene_name "AABR07000046.1"; gene_source "ensembl_havana"; gene_biotype "processed_transcript"; transcript_name "AABR07000046.1-202"; transcript_source "ensembl"; transcript_biotype "processed_transcript"; exon_id "ENSRNOE00000574883"; exon_version "1";

**Comment by gpertea** [comment]
Oops, sorry about that, my mistake -- I tested it only on the human data and made some silly assumptions there about the prefixes of the gene and transcript IDs (ENSG and ENST respectively). I'll fix this soon.

**Comment by ACastanza** [comment]
Ah, yeah, I've been burned by that (lack of) convention before as well.
If Ensembl followed their own rules Human should be ENSHSAG/T, to go with ENSMUSG/T, ENSRNOG/T etc, but they don't, another artifact preserved for backwards compatibility from the era of the only sequenced genes being from Human I'd assume. With the exception of Human, the ENS[nnn]G/T convention seems consistently adhered to though.

**Comment by gpertea** [comment]
I re-uploaded v0.12.4 (sorry it's still same version but the program was indeed updated), hopefully that error is fixed now -- please let me know if there are still issues.

**Comment by ACastanza** [comment]
I'm not seeing any change, as a note, I'm building this from source (since I'm running on a Mac) and it doesn't appear that the source file in the tar'ed release was updated, so if it was just the executable that was updated I'm not currently able to test it.

**Comment by gpertea** [comment]
Ah, I guess you're using the [Source code (tar.gz)](https://github.com/gpertea/gffread/archive/v0.12.4.tar.gz) which is the source automatically packaged by github and does not contain the updated gclib source files! The latest changes were actually in `gclib/gff.cpp` -- I guess you still used the older gclib files, directly from github, perhaps -- in which case you should do a `git pull` there before rebuilding gffread.

However the best/recommended way to build gffread from source is to use the larger source .tar.gz I provided for the release, just below the binary package(s), [gffread-0.12.4.tar.gz](https://github.com/gpertea/gffread/releases/download/v0.12.4/gffread-0.12.4.tar.gz). That one also contains all the necessary gclib includes, always up to date.
