### ISSUE TITLE
the fasta index generated from gffread is different from the one generated by samtools

### ISSUE THREAD

**Issue by grepinsight** [gpertea/gffread#7]
Thanks for making this program! Without it, it would have been a nightmare working with transcriptome.

I was using gffread to generate transcripts from a genome, and for some reason,  gffread was producing weird transcripts from the corresponding genome. 
After some debugging , I noticed that the __fasta index file(*.fa.fai) generated from gffread is different from the one generated by samtools__
```
# Old fa.fai file I had for the genome sequence
genome_seq1       8996366 138     70      71
genome_seq2       6298753 9125162 70      71
genome_seq3       3335877 15514036        70      71
genome_seq4       518634  18897707        70      71
genome_seq5       518104  19423889        70      71
genome_seq6       516100  19949533        70      71
genome_seq7       511760  20473144        70      71
genome_seq8       510996  20992353        70      71
genome_seq9       511190  21510787        70      71
genome_seq10       510612  22029418        70      71


# fa.fai generated using samtools v1.3 
genome_seq1       8996366 138     70      71
genome_seq2       6298753 9125162 70      71
genome_seq3       3335877 15514036        70      71
genome_seq4       518634  18897707        70      71
genome_seq5       518104  19423889        70      71
genome_seq6       516100  19949533        70      71
genome_seq7       511760  20473144        70      71
genome_seq8       510996  20992353        70      71
genome_seq9       511190  21510787        70      71
genome_seq10       510612  22029418        70      71

# fa.fai generated from gffread 
genome_seq1       9124886 138     71      71
genome_seq2       6388736 9125162 71      71
genome_seq3       3383533 15514036        71      71
genome_seq4       526044  18897707        71      71
genome_seq5       525506  19423889        71      71
genome_seq6       523473  19949533        71      71
genome_seq7       519071  20473144        71      71
genome_seq8       518296  20992353        71      71
genome_seq9       518493  21510787        71      71
genome_seq10       517907  22029418        71      71

```

**Comment by gpertea** [comment]
Are you by any chance using an old(er) version of gffread? Indeed this was bug reported a couple months ago (closed issue #5) but I thought this was fixed since then, and I just double-checked with v0.9.8c from here: http://ccb.jhu.edu/software/stringtie/gff.shtml#gffread
Could you please check if your version of gffread is from last year -- in which case it might have that bug still there. But please let me know if you're somehow running a recent version and *still* experience this issue.

**Comment by grepinsight** [comment]
@gpertea , 
Just confirmed that the version I used is 0.9.8c and the problem still persists.
```
$ gffread --version
0.9.8c
```

**Comment by gpertea** [comment]
And that bad .fai file was generated recently, with this version, not an older one, right? 
Is it possible to reproduce this on just a couple of records from that fasta file and share those wtih me ? I cannot reproduce this here. Also, what platform are you on, Linux or OS X ?

The version thing is muddying the waters a bit here too (my bad), as it is technically possible to report v0.9.8c while still being built with an old "gclib" folder (with the bug still there), if it was built from git repo without updating gclib properly.. But if that binary was built from the source package found on the official download page (or the pre-built binary from there was used) then there should be no confusion..
