### ISSUE TITLE
-F does not write the features info

### ISSUE THREAD

**Issue by husensofteng** [gpertea/gffread#71]
Hi,

Converting `GTF` to `FASTA` only writes the Transcript ID in the `FASTA` output headers whereas in a previous version that I have it installed (**v0.11.7**) it did.

I tried the following:

> gffread -F -g Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa -w Homo_sapiens.GRCh38.102.fa Homo_sapiens.GRCh38.102.gtf 

The reference files are from ENSEMBL

The output looks like:

> \>ENST00000456328.2
> GTTAACTTGCCGTCAGCCTTTTCTTTGACCTCTTCTTTCTGTTCATGTGTATTTGCTGTCTCTTAG....

**Comment by FabianDK** [comment]
I have the same issue for converting a fasta and gtf to protein seq.
`gffread -g genome.fasta -y protein.fasta file.gff -F`

I get the same headers in the fasta regardless of the -F option.

**Comment by husensofteng** [comment]
I tested a previous version of `gffread v0.11.6` and it worked fine so it seems to be an issue with the newer version(s). 

btw, to my knowledge `gffread` extracts DNA sequences not protein sequences.

**Comment by gpertea** [comment]
(@husensofteng , `-w` writes DNA sequence, `-y` writes the protein translation etc., see the usage message)

To the topic at hand: indeed, I had changed that functionality several months ago as I thought that shoving all the GFF attributes indiscriminately in the FASTA headers was usually undesired (and looked quite bad, I also disliked the redundancy of showing the attribute names all the time etc.)

However various GFF attributes can now be shown in the FASTA headers in a _more selective manner_ using the new `--table` option, where you can actually list the attributes (and other metadata) that the user wants written in the FASTA header. See the usage message (`gffread -h`) for the --table option, and let me know if you have a use case which is not served by the new `--table` option.

I do see as a possible issue for those who made use of the previous functionality that the attribute values specified in the `--table` option are now simply printed directly, tab delimited, _without the attribute names preceding them_ (and if an attribute is missing, a `.` (period) character is printed instead, so the number and order of columns in the FASTA header is still preserved as given in the `--table` option).  However the same information is now there (the attribute values), the user should just remember the attributes requested with the `--table` option and their order..

**Comment by husensofteng** [comment]
Thank you for the explanation and providing this great tool.

The issue is that I am using `gffread` in my pipeline where users can provide a `FASTA` file as input. Since the FASTA files are produced by users it is hard to control what order (with the `--table` option) they use to generate the `FASTA` file and thus it is not possible for the pipeline to parse the records unless each attribute value is linked to an attribute name.  

I understand that is not an issue of `gffread` and the current FASTA files look less redundant. However backward compatibility is very important to consider when releasing new versions to avoid breaking workflow executions! I think that is also a reason why ENSMEBLE always keeps those attribute names in the `ncrna` and `CDS` `FASTA` files.

**Comment by gpertea** [comment]
I can easily make it so in the FASTA files the output is written as _attr_name_=_attr_value_ as perhaps an additional option for the `--table` option. Or indeed revert the behavior for `-F` -- that would be the easiest and I guess the way to go (`-F` does ask for all attributes to be preserved, after all, if you want them in the FASTA files too, so be it ! :) )

I just am curious to understand your use case better: how are users generating the FASTA files in the workflow you are describing, are they simply instructed to use `gffread -F -w ...` ? Is it wrong of me to presume you only need to parse a few specifically targeted attributes from that FASTA header -- and in that case could you not give them the precise attribute names (and order) to use with `--table` option instead of just telling them to use `-F`?

**Comment by husensofteng** [comment]
Thank you for the reply. It would be really great if you could revert the -F behaviour. Obviously, if one does not want all attribute details they could skip that option.

As for my use case here, the specification is that the input FASTA file should have `transcript_idS=?`, `gene_name=?`, `transcript_biotypeSep=?`, etc included in the header. The user is free to obtain such FASTA file from public resources or with any tool (of course `gffread` is🥇) . Also, in the pipeline I use `gffread` to enable DNA sequence extraction directly from input types such as `GTF`.

Sorry for the trouble and thanks for considering this issue.

**Comment by gpertea** [comment]
In the last release (v0.12.6) `-F` option now prints again all the attributes in the FASTA file, but this time I decided to have them delimited by semicolon, as that's much easier/safer to parse (the former way of using space as delimiter was problematic when spaces were also found within some attribute values, while semicolons are normally escaped in a GFF3 anyway)
