### ISSUE TITLE
shorter transcript not discarded using -K

### ISSUE THREAD

**Issue by krabapple** [gpertea/gffread#78]
from the --help output
```
 -K   for -M option: also discard as redundant the shorter, fully contained
       transcripts (intron chains matching a part of the container)
```

I'm trying to understand why the shorter, 2-exon gene & transcript (i.e. gene 1-jg14458 and its children) in the locus created below  was not discarded in this merged output,  using gffread with  -M and -K options together:

` /gffread-0.12.6/gffread -M nogap1_augustus.hints.addnumber.gtf nogap2_augustus.hints.addnumber.gtf nogap3_augustus.hints.addnumber.gtf nogap4_augustus.hints.addnumber.gtf -K -o all_nogap_merged.Koption.gff --keep-genes -d nogap_dupinfo.Koption.txt --force-exons --attrs attribs.csv`

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/sulli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/sulli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

  |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
Contig0 | gffcl | locus | 10011148 | 10012407 | . | - | . | ID=RLOC_00010762;geneIDs=3-jg1193,1-jg14458,2-jg14614;transcripts=1-jg14458.t1,2-jg14614.t1
Contig0 | AUGUSTUS | gene | 10011148 | 10012251 | . | - | . | ID=1-jg14458;transcripts=1-jg14458.t1;locus=RLOC_00010762
Contig0 | AUGUSTUS | transcript | 10011148 | 10012251 | . | - | . | ID=1-jg14458.t1;Parent=1-jg14458;locus=RLOC_00010762
Contig0 | AUGUSTUS | exon | 10011148 | 10011523 | . | - | . | Parent=1-jg14458.t1
Contig0 | AUGUSTUS | exon | 10011683 | 10012251 | 0.72 | - | . | Parent=1-jg14458.t1
Contig0 | AUGUSTUS | CDS | 10011148 | 10011523 | . | - | 1 | Parent=1-jg14458.t1
Contig0 | AUGUSTUS | CDS | 10011683 | 10012251 | . | - | 0 | Parent=1-jg14458.t1
Contig0 | AUGUSTUS | gene | 10011148 | 10012407 | . | - | . | ID=2-jg14614;transcripts=2-jg14614.t1;locus=RLOC_00010762
Contig0 | AUGUSTUS | transcript | 10011148 | 10012407 | . | - | . | ID=2-jg14614.t1;Parent=2-jg14614;locus=RLOC_00010762
Contig0 | AUGUSTUS | exon | 10011148 | 10012407 | . | - | . | Parent=2-jg14614.t1
Contig0 | AUGUSTUS | CDS | 10011148 | 10012407 | . | - | 0 | Parent=2-jg14614.t1

</body>

</html>

Locus looks like this in IGV:

![image](https://user-images.githubusercontent.com/49412726/126081494-a8e979c9-661e-4a31-a9f3-b71de2b75f20.png)

**Comment by krabapple** [comment]
Investigating further, it appears it's to do with the way 'fully contained' is defined.  I confirmed that using -K definitely  does remove *some* transcripts.  Here is an example from the same merged gffs as above (I removed suprefluous 'exon' lines for clarity, as these models have no UTRs) . 

The upper locus was generated without -K, the lower one , using -K.  The lower version has deleted one transcript (1-jg10016.t1) whose start and end coordinates are entirely *within* (neither is coterminous) with boundaries of the longest transcript.  

I would like to have gffread also delete shorter transcripts that share one terminal coordinate with the longer  transcript.  That's what I was hoping -K would do.    In the case below, the resulting locus would consist of a single gene model. 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/sulli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/sulli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



  |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
Contig45_pilon_pilon | gffcl | locus | 1 | 2719 | . | - | . | ID=RLOC_00024213;geneIDs=4-jg6711,1-jg10016,1-jg10017,2-jg11172,3-jg12675;transcripts=4-jg6711.t1,2-jg11172.t1,1-jg10016.t1,1-jg10017.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 1 | 1031 | . | - | . | ID=4-jg6711;transcripts=4-jg6711.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 1 | 1031 | . | - | . | ID=4-jg6711.t1;Parent=4-jg6711;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 1 | 1031 | . | - | 0 | Parent=4-jg6711.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 71 | 2719 | . | - | . | ID=2-jg11172;transcripts=2-jg11172.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 71 | 2719 | . | - | . | ID=2-jg11172.t1;Parent=2-jg11172;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 71 | 2214 | . | - | 2 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | CDS | 2257 | 2719 | . | - | 0 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 91 | 2194 | . | - | . | ID=1-jg10016;transcripts=1-jg10016.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 91 | 2194 | . | - | . | ID=1-jg10016.t1;Parent=1-jg10016;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 91 | 2194 | . | - | 0 | Parent=1-jg10016.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 2237 | 2719 | . | - | . | ID=1-jg10017;transcripts=1-jg10017.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 2237 | 2719 | . | - | . | ID=1-jg10017.t1;Parent=1-jg10017;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 2237 | 2719 | . | - | 0 | Parent=1-jg10017.t1
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |
-K  
Contig45_pilon_pilon | gffcl | locus | 1 | 2719 | . | - | . | ID=RLOC_00024213;geneIDs=4-jg6711,1-jg10016,1-jg10017,2-jg11172,3-jg12675;transcripts=4-jg6711.t1,2-jg11172.t1,1-jg10017.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 1 | 1031 | . | - | . | ID=4-jg6711;transcripts=4-jg6711.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 1 | 1031 | . | - | . | ID=4-jg6711.t1;Parent=4-jg6711;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 1 | 1031 | . | - | 0 | Parent=4-jg6711.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 71 | 2719 | . | - | . | ID=2-jg11172;transcripts=2-jg11172.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 71 | 2719 | . | - | . | ID=2-jg11172.t1;Parent=2-jg11172;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 71 | 2214 | . | - | 2 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | CDS | 2257 | 2719 | . | - | 0 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | gene | 2237 | 2719 | . | - | . | ID=1-jg10017;transcripts=1-jg10017.t1;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | transcript | 2237 | 2719 | . | - | . | ID=1-jg10017.t1;Parent=1-jg10017;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 2237 | 2719 | . | - | 0 | Parent=1-jg10017.t1



</body>

</html>

**Comment by krabapple** [comment]
Investigating further, I wonder if  it's to do with the way 'fully contained' is defined.  I confirmed that using -K definitely  does remove *some* transcripts.  Here is an example from the same merged gffs as above (I removed superfluous 'gene' and 'exon' lines for clarity, these models have no UTRs) . 

The upper locus was generated without -K, the lower one , using -K.  The lower version has deleted one transcript (1-jg10016.t1) whose start and end coordinates are entirely *within* (neither end is coterminous with) boundaries of the longest transcript.  Trnascripts that are within the longest mRNA but share one coordinate with it, are kept. 

I would like to have gffread also delete shorter transcripts that share one terminal coordinate with the longer  transcript.  That's what I was hoping -K would do.    In the case below, the resulting locus would consist of a single gene model. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///D:/Users/sulli/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///D:/Users/sulli/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



  |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
Contig45_pilon_pilon | gffcl | locus | 1 | 2719 | . | - | . | ID=RLOC_00024213;geneIDs=4-jg6711,1-jg10016,1-jg10017,2-jg11172,3-jg12675;transcripts=4-jg6711.t1,2-jg11172.t1,1-jg10016.t1,1-jg10017.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 1 | 1031 | . | - | . | ID=4-jg6711.t1;Parent=4-jg6711;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 1 | 1031 | . | - | 0 | Parent=4-jg6711.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 71 | 2719 | . | - | . | ID=2-jg11172.t1;Parent=2-jg11172;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 71 | 2214 | . | - | 2 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | CDS | 2257 | 2719 | . | - | 0 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 91 | 2194 | . | - | . | ID=1-jg10016.t1;Parent=1-jg10016;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 91 | 2194 | . | - | 0 | Parent=1-jg10016.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 2237 | 2719 | . | - | . | ID=1-jg10017.t1;Parent=1-jg10017;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 2237 | 2719 | . | - | 0 | Parent=1-jg10017.t1
  |   |   |   |   |   |   |   |  
-K |   |   |   |   |   |   |   |  
Contig45_pilon_pilon | gffcl | locus | 1 | 2719 | . | - | . | ID=RLOC_00024213;geneIDs=4-jg6711,1-jg10016,1-jg10017,2-jg11172,3-jg12675;transcripts=4-jg6711.t1,2-jg11172.t1,1-jg10017.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 1 | 1031 | . | - | . | ID=4-jg6711.t1;Parent=4-jg6711;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 1 | 1031 | . | - | 0 | Parent=4-jg6711.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 71 | 2719 | . | - | . | ID=2-jg11172.t1;Parent=2-jg11172;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 71 | 2214 | . | - | 2 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | CDS | 2257 | 2719 | . | - | 0 | Parent=2-jg11172.t1
Contig45_pilon_pilon | AUGUSTUS | transcript | 2237 | 2719 | . | - | . | ID=1-jg10017.t1;Parent=1-jg10017;locus=RLOC_00024213
Contig45_pilon_pilon | AUGUSTUS | CDS | 2237 | 2719 | . | - | 0 | Parent=1-jg10017.t1



</body>

</html>

**Comment by gpertea** [comment]
gffread considers merging/removal of _transcripts_ only if they are _intron compatible_, that is, there are perfectly aligned intron coordinates between such transcripts -- obviously that implies that an intron start or end of a transcript cannot land in the middle of an exon of another (that contradicts the concept of _intron compatible_ as I assumed it -- though perhaps I should have made that more explicit).

From the info you shared it looks like you're expecting the 2-exon transcript `1-jg14458.t1` to be merged into the single-exon transcript `2-jg14614.t1`, just because the genomic span of the former is "contained" within the genomic span of the other, but that is not enough. The "redundancy reduction" principle behind the `-M` usage and its sub-options (like -K, -Q etc.) can only operate between "_intron redundant_" transcript structures (or overlapping single-exon transcripts), so it cannot be applied here.

**Comment by krabapple** [comment]
Thanks for the quick reply.  I think I understand now that introns in two gene models have to be perfectly aligned for an intron-containing model to be removed.  If two such models are *completely* aligned, -M will merge them.  If one is shorter than the other (but the intron is aligned) , -K will remove the shorter one.   It doesn't happen in my example above because only one model has an intron. Is that correct?

Can you explain/confirm what you mean by ' (or overlapping single-exon transcripts)" as regard application of -M and its sub options?  In the example below from my gffread outputs,  the input area of interest (from 4 gene modelling runs)  had 5 gene models with overlapping/nested boundary coordinates:

model 1:           1 - 1031   (1 exon)   - overlaps model 2/3 and 4

model 2/3:      71 - 2719    (2 exon)   -  2 identical models; overlaps models 1 and 5; CDS 1 nests model 4
      CDS 1 :      71 - 2214
      CDS 2:    2257- 2719

model 4:          91 - 2194   (1 exon)   - overlaps model 1;  is nested within CDS 1 of model 2/3

model 5:      2237 - 2719   (1 exon)   -  overlaps model 2/3

-M  clustered these as a single locus RLOC_00024213 -- I presume this is because they overlap?  It also reduced identical models 2/3 to a single model, as expected 

-K   removed model 4 .  I presume this is because it is fully nested within  CDS 1 of model 2/3?

The final locus after -K contains overlapping models 1, 2, and 5

**Comment by gpertea** [comment]
Indeed with `-M`  locus features are created by clustering of transcripts based on _exon overlaps_. (As a side note, this locus clustering can be also performed using the `--cluster-only` option, which does not discard/merge any transcripts).

`-M` was meant to merge "redundant" transcripts within such clusters, only those fully intron compatible -- i.e. with perfect intron chain match and boundary contained. Options `-K` and `-Q` are relaxing the requirements for a transcript to be considered "redundant" structurally, and thus be "swallowed" by another, larger transcript structure.  Note that for this relaxing operates slightly differently for single exon transcripts (SETs) vs multi-exon transcripts (METs). I put together a figure below trying to illustrate how the various option combinations affect the considerations of "redunancy" for METs and SETs -- the blue-colored transcripts are being "merged" into the larger black transcripts in these figures. 

A while ago I was also using gffread to merge "redundant" gene models, and in most cases using `-MKQ` combination is what I used, but for a more conservative approach you might consider just using `-M`. 

![gffread_M](https://user-images.githubusercontent.com/3372619/126249460-234c8085-0e31-45ab-8d90-200cea6bae57.png)

**Comment by gpertea** [comment]
Another way to look at the "intron compatibility" requirement for merging is like this: gffread will never merge two transcripts if there is at least one base (location) that is **exonic** in one transcript but **intronic** in the other.

**Comment by krabapple** [comment]
Thanks, this is very helpful. I still would lke to be clear on two matters

1) in my example, -K caused single-exon transcript #4 to disappear.  I assume it was 'swallowed' by CDS1 of multi-exon transcript  #2 , because that is the only entity that fully contains  transcript #4.  Is this the case?  Can an exon of a multi-exon transcript 'swallow' a single-exon transcript whose boundaries are contained within it?

2)  in addition to merging redundant transcripts, the locus created by -M includes multiple partially overlapping transcript.  What are the criteria for this? Is there a limit to how much overlap must exist for a transcript to be included in a locus,  and is there a limit to how many overlapping transcripts -M will include in a locus?

**Comment by krabapple** [comment]
As an experiment re question2 above, I omitted transcripts 2/3 from the input to -M.  In the new output, these two, which only partly overlap, were still included in the same locus

model 1:           1 - 1031   (1 exon)   - overlaps model  4
model 4:          91 - 2194   (1 exon)   - overlaps model 1

(model 5, which does not overlap with either  1 or 4,  was assigned its own locus)

So it does not appear that the 'strict boundary' for SET applies for merging?   How are the boundaries for a locus set?

**Comment by gpertea** [comment]
I think there is a confusion between _clustering_ transcripts into a locus versus _merging_ (discarding redundant) transcripts within a locus. The table/figure I attached above was meant to show how the blue transcripts were _merged_ into ("swallowed" by) the black ones according to the given "merge" options (-K and/or -Q).

However _clustering_ into loci has no structural restrictions at all (e.g. boundary containment), it's simply based on plain exonic overlaps (so it's not affected by -K/-Q options etc.), any partial exon overlap (even a 1-base one!) will put transcripts in the same locus (and transitive closure applies, it's not a _clique_ structure!). 

A locus is basically a "gene" and as such it can have multiple alternatively spliced transcripts (non-redundant isoforms) that can have only partial exon overlaps. The `-M` option (with it's -K and -Q sub-options) is there just to "cleanup" a locus, discarding the supposedly "redundant" isoforms. As I mentioned before, if one only wants the grouping of transcripts into loci (without the risk of data loss of the `-M` option), the `--cluster-only` option can be used instead. 

So to answer your last numbered questions:

1. Yes
2. As explained above, locus formation has only one simple rule: two transcripts having an exonic overlap are placed in the same locus. (_any_ exonic overlap will do, i.e. there are no containment restrictions etc.)

**Comment by krabapple** [comment]
Thank you.  Very clear now.
