### ISSUE TITLE
option --nc not supported

### ISSUE THREAD

**Issue by tbazilegith** [gpertea/gffread#97]
Hello Pertea,
I was trying to filter non coding sequences I got this error

gffread -E sample_annot/annot.gff --nc -o sample_nonCoding.gff

Error: invalid argument '--nc'
Thanks!
TJ

**Comment by gpertea** [comment]
What version are you using there (`gffread --version`)? And what platform? That argument seems to work on the current release version (in Linux at least).

**Comment by tbazilegith** [comment]
Hi Pertea,
I am running version gffread/0.9.8c on minION sequences on a linux terminal
Thanks!

**Comment by gpertea** [comment]
That is a very old version that likely does not have the `--nc` option properly implemented (even though it might be shown in the usage message, this could be an old bug). Could you perhaps download and run the latest precompiled Linux x86_64 version instead (0.12.7) ? That should work on most Linux x86_64 distros, even older ones.

**Comment by tbazilegith** [comment]
I already have version 0.12.7 on my system. I thought the 0.9.8c was recent than it. I'm going to load it
Thanks!

**Comment by tbazilegith** [comment]
It's working.
Thanks!
